# Generated by Django 3.2.25 on 2024-10-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('EDT', 'EDT Lessons'), ('Pre-Test', 'Pre-Test Lessons'), ('Car Hire', 'Car Hire for Tests')], max_length=50)),
            ],
        ),
    ]
